name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 */6 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  org:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: pot-app-metrics.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          template: organizations
          user: pot-app
  pot-desktop-contributions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: pot-desktop-contributions.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          template: repository
          user: pot-app
          repo: pot-desktop
          plugin_contributors: yes
          plugin_contributors_contributions: yes
  pot-desktop-stars:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: pot-desktop-stars.svg
          token: ${{ secrets.TOKEN }}
          base: ""
          template: repository
          user: pot-app
          repo: pot-desktop
          plugin_stargazers: yes
          plugin_stargazers_charts_type: graph
